apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-stack.fullname" . }}-mcpgateway
  labels:
    {{- include "mcp-stack.labels" . | nindent 4 }}
  {{- with .Values.mcpContextForge.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mcpContextForge.service.type }}
  selector:
    app: {{ include "mcp-stack.fullname" . }}-mcpgateway
  ports:
    - name: http
      port: {{ .Values.mcpContextForge.service.port }}
      targetPort: {{ .Values.mcpContextForge.containerPort }}
      protocol: TCP
